### ISSUE TITLE
Package install filed

### ISSUE THREAD

**Issue by mureev** [ramusus/kinopoiskpy#11]
Hey,

I got this install error:

> File "<string>", line 17, in <module>
> File "C:\Users\Constantine\AppData\Local\Temp\pycharm-packaging345199152772768734.tmp\kinopoiskpy\setup.py", line 5, in <module>
> 
> version=**import**('kinopoisk').**version**,
> 
> File "C:\Users\Constantine\AppData\Local\Temp\pycharm-packaging345199152772768734.tmp\kinopoiskpy\kinopoisk__init__.py", line 1, in <module>
> 
> from movie import Movie, Trailer
> 
> ImportError: No module named 'movie'

**Comment by fantomnotabene** [comment]
I have the same error now while installing via pip on Windows:
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 1086:

**Comment by fantomnotabene** [comment]
Скачал архивом, поправил в 7 строке в install.py на:
long_description=open('README.md',encoding='utf-8').read()
Так установилось.

**Comment by moran-x** [comment]
До сих пор актуально, ошибке 3 года и ни как не можете исправить....

**Comment by ramusus** [comment]
fixed
