### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by ghostku** [ramusus/kinopoiskpy#16]
Не могу подключить модуль

    Traceback (most recent call last):
    File "tvshows.py", line 11, in <module>
    from kinopoisk import Movie
    ImportError: cannot import name 'Movie'

Также и с 'Person'

**Comment by ramusus** [comment]
поправил документацию

**Comment by ramusus** [comment]
Попробуйте
from kinopoisk.movie import Movie

**Comment by ghostku** [comment]
Заработало немного

**Comment by ghostku** [comment]
Теперь при получении данных каждый раз выдает предупреждение

>C:\tools\python\lib\site-packages\beautifulsoup4-4.4.0-py3.4.egg\bs4\__init__.py:166: >UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for >this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a >different virtual environment, it may use a different parser and behave differently.
>
>To get rid of this warning, change this:
>
>BeautifulSoup([your markup])
>
>to this:
>
>BeautifulSoup([your markup], "lxml")
