### ISSUE TITLE
BeatifullSoup Warning

### ISSUE THREAD

**Issue by ghostku** [ramusus/kinopoiskpy#18]
Теперь при получении данных каждый раз выдает предупреждение

>C:\tools\python\lib\site-packages\beautifulsoup4-4.4.0-py3.4.egg\bs4__init__.py:166:  UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for >this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

>To get rid of this warning, change this:
>
>BeautifulSoup([your markup])
>
>to this:
>
>BeautifulSoup([your markup], "lxml")

Как бы от него избавится?

**Comment by ramusus** [comment]
убрал предупреждение
