### ISSUE TITLE
Movie.directors не работает

### ISSUE THREAD

**Issue by gorelikspb** [ramusus/kinopoiskpy#32]
Пытаюсь получить режиссера по id фильма. Выдает пустой результат, хотя на КП он есть. Это нормально?

**Comment by ramusus** [comment]
Нет, не нормально

**Comment by gorelikspb** [comment]
что я делаю не так?

    m = Movie(id=mov.id)
    m.get_content('main_page')
    print (m.directors)

**Comment by ramusus** [comment]
ммм, не знаю

**Comment by gorelikspb** [comment]
Сформулирую вопрос получше

`from kinopoisk.movie import Movie

m = Movie(id=160977)
m.get_content('main_page')
print (m.title) #вывод: Апокалипсис
print (m.directors) #вывод: []`

почему последняя строка ничего не выводит?

**Comment by gorelikspb** [comment]
:(

**Comment by anton-ryzhov** [comment]
Судя по сорцам — это поле ни сейчас, ни в прошлом никогда не заполнялось

**Comment by ramusus** [comment]
Зарелизил 0.6.11 с поддержкой режиссеров, продюссеров и т.д.
