### ISSUE TITLE
movie.id = None

### ISSUE THREAD

**Issue by oct2i** [ramusus/kinopoiskpy#34]
Встретил у некоторых фильмов, что id = None.
А точнее: Геошторм (2017), Звездачи (2017), Бабадук (2014), Скрюченный домишко (2017), Субурбикон (2017).

```
>>> from kinopoisk.movie import Movie
>>> movie_list = Movie.objects.search('Геошторм')
>>> len(movie_list)
1
>>> print(movie_list[0].title)
Геошторм
>>> print(movie_list[0].id)
None
```

**Comment by ramusus** [comment]
Попробуйте обновить до последней версии, я поправил это недавно

**Comment by ramusus** [comment]
Закрываю, открывайте если все еще актуально

**Comment by MrKsey** [comment]
Все-равно  id = None.
Например, "Варкрафт".
Т.е. когда поиск находит только один фильм, то сразу показывает страницу фильма, а не список.
Пока борюсь с этим путем добавления к названию фильма текущего года и выполнением повторного запроса.

**Comment by ramusus** [comment]
@MrKsey Да, вы описали все верно, но это не значит что id должен быть пустым. Приведите пож-та пример кода, как сделать поиск, чтобы в результате будет пустой id.

**Comment by MrKsey** [comment]
Вот такой код:
```
from kinopoisk.movie import Movie
movie_list = Movie.objects.search('Варкрафт')
print(movie_list[0].id)
```
У меня версия 0.6.11, установлена через pip install.
Python такой: 

> 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32

**Comment by ramusus** [comment]
Спасибо за репорт, поправил в https://github.com/ramusus/kinopoiskpy/commit/a578d79fde22721a9dd82169039251e2f1bb2fd2
чуть позже обновлю версию до 0.6.12

**Comment by ramusus** [comment]
выложил 0.6.12
