### ISSUE TITLE
Movie

### ISSUE THREAD

**Issue by lerevolte** [ramusus/kinopoiskpy#35]
Приветствую!
`Movie.objects.search('Redacted')` - работает корректно
Но:
`Movie(id=2727).get_content('main_page')` - возвращает None на любой id

**Comment by ramusus** [comment]
`get_content` не должна возвращать результат, она лишь наполняет данными объект
```
m = Movie(id=2727)
m.get_content('main_page')
print(m)
```

**Comment by lerevolte** [comment]
Да, все именно так. Только объект не заполняется. 
Например `{{m.title}}` не выводит ничего.

**Comment by ramusus** [comment]
какая версия библиотеки и python?

**Comment by goshulina** [comment]
Та же проблема что и у lerevolte

**Comment by goshulina** [comment]
Окей
Еще одна трабла. Вроде как по всем фильмам основная инфа достается
Но:
```
y = Movie(id=694633)
y.get_content('main_page')
print(y.premiers)
```
выдает название класса
`<kinopoisk.movie.MoviePremiersManager object at 0x10c53b588>`
вместо премьеры.
Дата премьеры есть: https://www.kinopoisk.ru/film/bolnitsa-nikerboker-2014-818708/
Это ли не потому что в kinopoiskpy/kinopoisk/movie/sources.py : 

```
date = premier_soup.find('meta', {'itemprop': 'startDate'})['content']
        try:
            self.instance.release = parser.parse(date)
        except Exception:
            pass
```
объект data не заполняется?

**Comment by ali-man** [comment]
Здравствуйте! не могу пропарсить /photos/
movie.get_content('photos')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/.../site-packages/kinopoisk/utils.py", line 107, in get_content
    self.get_source_instance(name, instance=self).get()
  File "/.../site-packages/kinopoisk/utils.py", line 297, in get
    raise ValueError('Parse error. Do not found posters for movie %s' % (self.instance.get_url('posters')))
ValueError: Parse error. Do not found posters for movie http://www.kinopoisk.ru/film/278229/posters/

**Comment by ali-man** [comment]
а проще говоря, как получить ссылка на скриншоты фильма ?

**Comment by goshulina** [comment]
Забейте на этот репо
Пишите свои парсеры

**Comment by ramusus** [comment]
@tatyanavolkova библиотека работает корректно в py2.7 и py3.4 https://travis-ci.org/ramusus/kinopoiskpy

@goshulina Метод `Movie.premiers.all` возвращает список всех премьер c датами. 
```In [7]: Movie.premiers.all()
Out[7]: 
[Трудно быть Богом (), -,
 Лондонские поля (London Fields), 2018,
 Проклятие монахини (The Nun), 2018,
...]
In [8]: w = Movie.premiers.all()
In [9]: w[0].release
Out[9]: datetime.datetime(2018, 9, 20, 0, 0)
```

@ali-man 
```
In [10]: m = Movie(id=278229)
In [11]: m.get_content('posters')
In [12]: m.posters
Out[12]: 
['https://st.kp.yandex.net/im/poster/7/9/1/kinopoisk.ru-Redacted-791507.jpg',
 'https://st.kp.yandex.net/im/poster/7/3/2/kinopoisk.ru-Redacted-732751.jpg',
 'https://st.kp.yandex.net/im/poster/6/9/8/kinopoisk.ru-Redacted-698349.jpg',
 'https://st.kp.yandex.net/im/poster/6/9/4/kinopoisk.ru-Redacted-694251.jpg',
 'https://st.kp.yandex.net/im/poster/6/8/8/kinopoisk.ru-Redacted-688685.jpg',
 'https://st.kp.yandex.net/im/poster/6/8/7/kinopoisk.ru-Redacted-687510.jpg',
 'https://st.kp.yandex.net/im/poster/6/6/9/kinopoisk.ru-Redacted-669451.jpg',
 'https://st.kp.yandex.net/im/poster/6/1/5/kinopoisk.ru-Redacted-615753.jpg',
 'https://st.kp.yandex.net/im/poster/6/1/0/kinopoisk.ru-Redacted-610816.jpg']
```

**Comment by ali-man** [comment]
о постерах в описании есть и с этим нет проблем
я про скриншоты фильма, вот ссылка, чтобы было наглядней
https://www.kinopoisk.ru/film/chelovek-pauk-2002-838/screenshots/

**Comment by ali-man** [comment]
хорошо, если до меня уже не скинут )
