### ISSUE TITLE
How to get trailers

### ISSUE THREAD

**Issue by johnMontor** [ramusus/kinopoiskpy#37]
Приветствую, ramusus!
Не выходит получить информацию о трейлерах: movie.get_content('trailers')
AttributeError: 'MovieTrailersPage' object has no attribute 'content_name'

При том, что movie.get_content('posters') и всё остальное без нареканий.
Что-то делаю не так?

![001](https://user-images.githubusercontent.com/39031529/44188831-83650680-a128-11e8-8e9b-74c0a7ef8e2d.PNG)

**Comment by ramusus** [comment]
Кинопоиск поменял формат отображения трейлеров и получение трейлеров сломалось. Тесты написаны, но закомментированы. Если у вас есть желание и время, то я буду рад принять PR с фиксом

**Comment by ramusus** [comment]
Откомментировать тесты для трейлеров и сделать так, чтобы они проходили без
ошибок. Потом открыть PR с правками для ревью

**Comment by ramusus** [comment]
Зарелизил 0.7.5. Всем спасибо за участие!
