### ISSUE TITLE
BeautifulSoup 'lxml' instead of 'html.parser' 

### ISSUE THREAD

**Issue by anmv** [ramusus/kinopoiskpy#38]
Подскажи, почему используется lxml? Он превращает страницу в набор символов и парсинг полностью ломается. После замены на html.parser всё работает.
Why use lxml parser, it isn't work? After replace on html.parser - all ok
[Ubuntu 18.04, Python 3.6.5, beautifulsoup4 4.6.1, kinopoiskpy 0.7.2 ]
Есть время поправить это, вопрос в том не сломается ли у других.
Так же можно в информацию о фильме добавить даты релизов в РФ, в Мире на DVD

**Comment by ramusus** [comment]
Вообще у было меня в планах полностью избавится от BeautifulSoup в пользу XPATH. Но это быстро не получится, а пока действительно `html.parser` работает лучше. Я поправлю в ближайшее время

**Comment by ramusus** [comment]
Зарелизил версию 7.3
