### ISSUE TITLE
Unknown html layout

### ISSUE THREAD

**Issue by dan-an** [ramusus/kinopoiskpy#41]
В ответ на запрос отдает 
Unknown html layout found by request "http://www.kinopoisk.ru/index.php?level=7&from=forma&result=adv&m_act%5Bfrom%5D=forma&m_act%5Bwhat%5D=content&m_act%5Bfind%5D=%D0%93%D0%BE%D0%BB%D0%BE%D0%B4"

**Comment by ramusus** [comment]
какой запрос? как воспроизвести ошибку?
