### ISSUE TITLE
Слетела кодировка

### ISSUE THREAD

**Issue by anton-bozhina** [ramusus/kinopoiskpy#48]
Результаты перестали возвращаться в нормальной кодировке. В коде ничего не менял, модули не обновлял.

**Comment by AleckNormanOnim** [comment]
Здравствуйте! Тот же самый баг. Пример возвращаемых данных - **РљРёРј РЎСѓ-С...С‘РЅ** - так отображается кириллица.

**Comment by AleckNormanOnim** [comment]
Исправляется, если в **utils.py** (строка _#257_):
`self.content = response.content.decode('windows-1251', 'ignore')`
заменить на
`self.content = response.content.decode('utf-8')`

**Comment by imerr0r** [comment]
> 
> 
> Исправляется, если в **utils.py** (строка _#256_):
> `self.content = response.content.decode('windows-1251', 'ignore')`
> заменить на
> `self.content = response.content.decode('utf-8')`
> 

Подтверждаю, фикс работает, но пришлось заменить 'windows-1251' на 'utf8' не только на 256 строке, а ВСЕ в файле utils.py

**Comment by ramusus** [comment]
Прощу прощения за задержку, версия 8.2 с фиксом выпущена.
