### ISSUE TITLE
Как получить возрастной рейтинг?

### ISSUE THREAD

**Issue by nikminer** [ramusus/kinopoiskpy#53]
Никак не могу понять как получить возрастной рейтинг фильма. По идеи нужно прописать что-то вроде:
`movie.audience`
Но тот возвращается только пустой лист...
Функция get_content('audience'), тоже не находит... Как можно получить возрастной рейтинг фильма?

**Comment by ramusus** [comment]
К сожалению библиотека не поддерживает этот функционал. PR приветствуется
