### ISSUE TITLE
'Movie' object has no attribute 'career'

### ISSUE THREAD

**Issue by fatklass** [ramusus/kinopoiskpy#55]
Последние пару дней часто выпадает ошибка:
'Movie' object has no attribute 'career'

**Comment by ramusus** [comment]
Библиотека была обновлена, многие ошибки поправлены здесь https://github.com/ramusus/kinopoiskpy/pull/66. Если проблема будет повторяться, открывайте тикет заново и лучше с кодом как воспроизвести ошибку.
